package funxy_test

import (
	"os"
	funxy "github.com/funvibe/funxy/pkg/embed"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"testing"
)

func TestSpawnVM_DefaultIDsAreUniqueUnderConcurrency(t *testing.T) {
	code := `
import "lib/time"

while true {
    time.sleepMs(500)
}
`
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "worker.lang")
	if err := os.WriteFile(path, []byte(code), 0644); err != nil {
		t.Fatalf("write worker: %v", err)
	}

	hyp := funxy.NewHypervisor()
	hyp.RegisterCapabilityProvider(func(cap string, vmInstance *funxy.VM) error {
		return nil
	})

	const workers = 24
	ids := make([]string, 0, workers)
	errCh := make(chan error, workers)
	idCh := make(chan string, workers)
	var wg sync.WaitGroup

	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			id, err := hyp.SpawnVM(path, map[string]interface{}{
				"capabilities": []interface{}{"lib/time"},
			})
			if err != nil {
				errCh <- err
				return
			}
			idCh <- id
		}()
	}
	wg.Wait()
	close(errCh)
	close(idCh)

	for err := range errCh {
		t.Fatalf("concurrent SpawnVM failed: %v", err)
	}
	for id := range idCh {
		ids = append(ids, id)
	}
	if len(ids) != workers {
		t.Fatalf("expected %d IDs, got %d", workers, len(ids))
	}

	seen := make(map[string]struct{}, workers)
	for _, id := range ids {
		if _, exists := seen[id]; exists {
			t.Fatalf("duplicate vm id generated: %s", id)
		}
		seen[id] = struct{}{}
	}

	numbers := make(map[int]struct{}, workers)
	for _, id := range ids {
		if !strings.HasPrefix(id, "vm_") {
			t.Fatalf("unexpected autogenerated id format: %q", id)
		}
		n, err := strconv.Atoi(strings.TrimPrefix(id, "vm_"))
		if err != nil {
			t.Fatalf("failed to parse vm id %q: %v", id, err)
		}
		numbers[n] = struct{}{}
	}
	for i := 1; i <= workers; i++ {
		if _, ok := numbers[i]; !ok {
			t.Fatalf("missing autogenerated id vm_%d (ids=%v)", i, ids)
		}
	}

	for _, id := range ids {
		_, _ = hyp.KillVM(id, false, 1000)
	}
}
