package pipeline

import (
	"github.com/funvibe/funxy/internal/ast"
	"github.com/funvibe/funxy/internal/diagnostics"
	"github.com/funvibe/funxy/internal/symbols"
	"github.com/funvibe/funxy/internal/typesystem"
)

// PipelineContext holds all the data passed between pipeline stages.
type PipelineContext struct {
	SourceCode    string
	FilePath      string // Path to the source file (if any)
	TokenStream   TokenStream
	AstRoot       ast.Node
	SymbolTable   *symbols.SymbolTable         // Add the symbol table here
	TypeMap       map[ast.Node]typesystem.Type // Stores inferred types for expressions
	ResolutionMap map[ast.Node]symbols.Symbol  // Stores resolved symbols for identifiers
	Errors        []*diagnostics.DiagnosticError

	// Trait default method implementations: "TraitName.methodName" -> FunctionStatement
	TraitDefaults map[string]*ast.FunctionStatement

	// Operator -> Trait mapping for dispatch: "+" -> "Add", "==" -> "Equal"
	OperatorTraits map[string]string

	// Trait implementations: trait -> [InstanceDef] (MPTC support)
	TraitImplementations map[string][]symbols.InstanceDef

	// Module loader - shared between analyzer and evaluator
	// Using interface{} to avoid import cycle with modules package
	Loader interface{}

	// Module for entry package execution (set when FilePath is an entry file)
	// Stored as interface{} to avoid import cycle with modules package
	Module interface{}

	// BytecodeChunk generated by compiler (optional)
	// Using interface{} to avoid import cycle with vm package
	BytecodeChunk interface{}

	// IsTestMode indicates if we are running in test mode (enables test builtins)
	IsTestMode bool

	// IsEvalMode indicates -e flag: expression execution mode
	IsEvalMode bool

	// StdinData holds pre-read stdin data for -e mode (injected as `stdin` variable)
	StdinData *string
}

// NewPipelineContext creates and initializes a new PipelineContext.
func NewPipelineContext(source string) *PipelineContext {
	return &PipelineContext{
		SourceCode:           source,
		SymbolTable:          symbols.NewSymbolTable(),
		TypeMap:              make(map[ast.Node]typesystem.Type),
		ResolutionMap:        make(map[ast.Node]symbols.Symbol),
		Errors:               []*diagnostics.DiagnosticError{},
		TraitDefaults:        make(map[string]*ast.FunctionStatement),
		OperatorTraits:       make(map[string]string),
		TraitImplementations: make(map[string][]symbols.InstanceDef),
	}
}
